version: '3.4'

services:
  nginx:
    # https://hub.docker.com/_/nginx
    # https://hub.docker.com/layers/nginx/library/nginx/1.17.7-alpine/images/sha256-2911ad2d54f4cf4dc7ad21af122c1eefce16836a34be751c63351ca1fb452d57
    image: nginx@sha256:2911ad2d54f4cf4dc7ad21af122c1eefce16836a34be751c63351ca1fb452d57
    ports:
      - "8000:8000"
    volumes:
      - ./backend-project/contrib/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static
      - media:/media
    depends_on:
      - web

  db:
    # https://hub.docker.com/_/postgres
    # https://hub.docker.com/layers/postgres/library/postgres/12.1-alpine/images/sha256-acc27976001fac260a2e6e06170e70b7e667cdd85f16ee7355de0d47dcb990ae
    image: postgres@sha256:acc27976001fac260a2e6e06170e70b7e667cdd85f16ee7355de0d47dcb990ae
    expose:
      - "5432"
    volumes:
      - ./backend-project/contrib/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      # /var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'

  web:
    build:
      context: ./backend-project
    depends_on:
      - db
    volumes:
      - ./backend-project:/code
      - static:/code/static
      - media:/code/media
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/small_eod
      # SECRET_KEY
      # DJANGO_ALLOWED_HOSTS
    expose:
      - "8000"

volumes:
  static:
  media:
