name: JavaScript files

on:
  push:
    paths:
    - 'frontend-project/**'
    - '.github/**'
  pull_request:
    paths:
    - 'frontend-project/**'
    - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: make frontend_install
    - name: Lint
      run: make frontend_lint
    - name: Test
      run: make frontend_test
    - name: Build
      run: make frontend_build
      env:
        COMMIT_SHA: '{{github.sha}}'
        COMMIT_BRANCH: '{{github.ref}}'
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs:
      - test
    steps:
    - uses: actions/checkout@v1
    - name: Setup H1-CLI
      uses: ./.github/actions/h1-cli
    - uses: webfactory/ssh-agent@v0.3.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Inject website ssh-hostkey
      run: echo '${{ secrets.SSH_KNOWN_HOSTS }}' >> ~/.ssh/known_hosts;
    - name: Deploy update
      run: ./scripts/deploy_frontend.sh
      env:
        HYPERONE_ACCESS_TOKEN_SECRET: ${{ secrets.HYPERONE_TOKEN }}
        HYPERONE_PROJECT: '587707232a57b6fd80f04bc1'
