name: Django application

on:
  push:
    paths:
    - 'backend-project/**'
    - '.github/**'
    - '**/docker-compose.yml'
  pull_request:
    paths:
    - 'backend-project/**'
    - '.github/**'
    - '**/docker-compose.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: make lint
    - name: Build
      run: make backend_build
    - name: Migration check
      run: make backend_check
    - name: Show settings
      run: ./scripts/show_backend_settings.sh
    - name: Diff OpenAPI
      run: ./scripts/show_diff_openapi.sh
    - name: Wait for services
      run: make wait_backend
    - name: Python test
      run: make test
    - name: System test
      run: ./scripts/test/integration.sh
    - name: Send coverage report
      run: make -C backend-project coverage_send
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      if: github.event_name == 'push'
    - name: 'Archive OpenAPI specification'
    - run: ./scripts/save_openapi.sh
    - uses: actions/upload-artifact@v2
      with:
        name: openapi
        path: ./openapi.*
    - name: Docker-compose logs
      run: docker-compose logs
      if: failure()
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs:
      - test
    steps:
    - uses: actions/checkout@v1
    - name: Build production image
      run: docker build --target prod -t docker-registry.siecobywatelska.pl/small_eod/backend:latest backend-project/
    - name: "Docker login"
      env:
        DOCKER_REGISTRY_URL: docker-registry.siecobywatelska.pl
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY_URL}
    - name: Push image
      run: docker push docker-registry.siecobywatelska.pl/small_eod/backend:latest
    - name: Trigger SDK regenerate
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.SDK_REPO_TOKEN }}
        event-type: pushed
        repository: watchdogpolska/small-eod-sdk-javascript
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs:
      - test
    steps:
    - uses: actions/checkout@v1
    - name: Setup H1-CLI
      uses: ./.github/actions/h1-cli
    - uses: webfactory/ssh-agent@v0.3.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Inject website ssh-hostkey
      run: cat .github/h1-known-hosts > ~/.ssh/known_hosts;
    - name: Deploy update
      run: ./scripts/deploy_backend.sh
      env:
        HYPERONE_ACCESS_TOKEN_SECRET: ${{ secrets.HYPERONE_TOKEN }}
        HYPERONE_PROJECT: '587707232a57b6fd80f04bc1'
