name: Django application

on: [push]

jobs:
  django:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pyupgrade
      run: make pyupgrade
    - name: Lint
      run: make lint
    - name: Build
      run: make build
    - name: Migration check
      run: make check
    - name: Show settings
      run: make settings
    - name: Build & test
      run: chmod +x ./backend-project/contrib/github/script.sh && ./backend-project/contrib/github/script.sh
